---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: quote-service-policy
  namespace: quote-app
  labels:
    team: app-team
    env: production
spec:
  endpointSelector:
    matchLabels:
      app: quote-service
  ingress:
    # allow only traffic proxied through the Cilium Gateway (north-south L7 proxy)
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
