---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: argocd-egress
  labels:
    team: platform
    env: production
spec:
  description: "Allow ArgoCD control plane to reach kube-apiserver and the internet (git repos)"
  endpointSelector:
    matchLabels:
      any:io.kubernetes.pod.namespace: argocd
  egress:
    - toEndpoints:
        - matchLabels:
            any:io.kubernetes.pod.namespace: kube-system
            any:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
    - toEntities:
        - kube-apiserver
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
