---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny
  labels:
    team: platform
    env: production
spec:
  description: "Default deny all ingress and egress for all pods"
  endpointSelector: {}
  ingress:
    - fromEntities:
        - cluster
  egress:
    - toEntities:
        - cluster
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-gateway-ingress
  namespace: kube-system
  labels:
    team: platform
    env: production
spec:
  description: "Allow external traffic into Cilium Gateway Envoy pods only"
  endpointSelector:
    matchLabels:
      k8s-app: cilium-envoy
  ingress:
    - fromEntities:
        - world
        - cluster
