---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny
  labels:
    team: platform
    env: production
spec:
  description: "Default deny for all pods except quote-app (fully zero-trust via its own CNP)"
  endpointSelector:
    matchExpressions:
      - key: any:io.kubernetes.pod.namespace
        operator: NotIn
        values:
          - quote-app
  ingress:
    - fromEntities:
        - cluster
  egress:
    - toEntities:
        - cluster
