---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote-service
  namespace: argocd
  labels:
    team: app-team
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oceans2001/cilium-k8s-platform.git
    targetRevision: HEAD
    path: apps/quote-service/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: quote-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
